### ISSUE TITLE
Switch to REST-API

### ISSUE THREAD

**Issue by rck** [beornf/linstor-docker-volume#1]
Hi beornf,

I saw this repo because you sent a PR for the linstor-server. This is awesome! I'm the maintainer of the "official" [linstor-docker-volume plugin](https://github.com/LINBIT/linstor-docker-volume), and I also co-maintain golinstor. So some comments/suggested improvements:

The "old" golinstor uses the linstor-client to do its actions. I saw that you use the "lade.io" repos to get the client. This version is very outdated and I guess it would not even work with a recent linstor controller. The old one used probuf + a custom protocol, recent client and server use a [REST-API](https://app.swaggerhub.com/apis-docs/Linstor/Linstor/1.0.5).

The good news is that golinstor now also provides a [REST client](https://godoc.org/github.com/LINBIT/golinstor/client). It is pretty "low level", but IMO the way forward (we already transitioned our CSI plugin to it). We might remove/or at least substantially change the high level abstraction of golinstor.

Do you want to work on the plugin together? Maybe we could eventually put it under some "LINBIT umbrella" and make this one the default. For historic reasons the official one started in Python, but I'd be all in to switch it to Go. Does any of that sound interesting? :-D.

**Comment by beornf** [comment]
Hi @rck,

I started this repo last year as I wanted to integrate Linstor volumes as a Docker managed plugin https://docs.docker.com/engine/extend/. As far as I remember Docker swarm only supports Docker managed plugins and not legacy plugins.

I looked into the REST API and saw it only supports HTTP for now? Since another one of my requirements is mutual SSL authentication for the client-controller I added client key support to the outdated python client api as a stop gap.

I'd be happy to work with you on doing an official plugin in Go 👍. I have the above quirky requirements and really dig Linstor and DRBD so look forward to helping out and deprecating this repo.

**Comment by rck** [comment]
Hi @beornf,

sounds great! You are right, AFAIK the REST-API is currently http only. I will talk to the linstor-server people and see what they have to say. I will create a tracking ticket for that on linstor-server and reference this one. Please give me some time, this will happen early/mid next week. And when this is resolved, we have a clean path forward. Actually switching to the http-only version could start now. I guess the changes are then pretty minimal.

I suggest that we get it in shape here before we move it (if you then like) to the LINBIT namespace. We have to be a bit careful, whatever shows up under LINBIT is immediately used :-D

**Comment by beornf** [comment]
Hi @rck,

Okay let me know about linstor-server next week either here or on the PR I created over there https://github.com/LINBIT/linstor-server/pull/62.

So I have a few steps in mind going forward with the REST-API and golinstor:
- Switch to alpine docker image and remove the dependency on python linstor-client (final plugin would have e2fsprogs, xfsprogs & a golang binary)
- Decide on how to configure the plugin for static settings which could be via a mounted file `/etc/linstor/docker-volume.conf` and/or environment variables (i.e. LS_CONTROLLERS)
- Determine required driver options for volumes e.g. diskless_on_remaining, auto_place, storage_pool, size_kib, fs_type, replicas_on_same etc.
- Update driver commands https://docs.docker.com/engine/extend/plugins_volume/ to use the latest version of golinstor REST-API
- Changes to documentation to be ready under LINBIT
- Publish as an official docker volume plugin on https://hub.docker.com/ would be nice

**Comment by rck** [comment]
Hi @beornf,

Yes, all of that sounds good to me. As discussed I will make sure that the REST-API can be exposed via https and keep you somehow in the loop. Then I prepare support for that in golinstor.

**Comment by rck** [comment]
I talked to the LINSTOR people, https for the REST-API is on their TODO list.

**Comment by beornf** [comment]
Great I'll look into doing the above changes in a couple weeks.

**Comment by rck** [comment]
@beornf finally the first part of https/authentication landed in LINSTOR (v0.9.13) and golinstor as on master.

LINSTOR documentation for creating/configuring https can be found here: https://docs.linbit.com/docs/users-guide-9.0/\#s-linstor-rest-api

golinstor always supported https, because the design allowed to pass in a http.Client, so it was always up to the user to configure https. There is an example here: https://godoc.org/github.com/LINBIT/golinstor/client\#ex-package--Https

IIRC you also want to authenticate the client, is that correct? What LINSTOR supports as of now is setting the basic auth header (there is an example on godoc as well), but as of now this triggers LDAP auth in the LINSTOR controller. We started with LDAP because of a user request. I'm thinking about proposing a simple htpasswd file, and/or calling an external command with the username/password in the auth header. Would that be in you interest or do you need/want somthing different? But I hope with having initial https, this is something you can begin switching to golinstor/REST.

**Comment by beornf** [comment]
@rck The https/authentication support in LINSTOR sounds great. I'm going to start working on switching to golinstor/REST now and also supporting optional two way SSL authentication (configured with client certificate, private key and ca certificate files).

For basic auth credentials these can be added as a username/password in the static config file e.g. `/etc/linstor/docker-volume.conf` and/or environment variables `LS_USERNAME`, `LS_PASSWORD` would you agree?

Currently I am self-signing SSL certificates as I'm not familiar with setting up LDAP and a htpasswd file seems less secure than short-lived client certificates.

**Comment by beornf** [comment]
@rck I've completed the migration to golinstor REST-API and tested the plugin works for my requirements. The configuration is read from `/etc/linstor/docker-volume.conf`, plugin environment variables and command options.

Can you review the driver and let me know your thoughts on the overall design. Then we can start moving this under the LINBIT umbrella?

**Comment by rck** [comment]
This is good news. Currently I'm on vacation, so this will take 2 weeks till I'm back. But it is on my TODO for when I'm back.

Regards, rck

**Comment by rck** [comment]
Thanks for implementing this, I think we can close this one now. I did an initial review and will open some issues PRs soon.
