### ISSUE TITLE
linstor-docker-volume plugin can not run on ARM ubuntu18.04

### ISSUE THREAD

**Issue by kevinwd** [beornf/linstor-docker-volume#10]
Test environment：

1.ARM64
2.root@node43:/home/horatio# cat /proc/version
Linux version 4.15.0-76-generic (buildd@bos02-arm64-060) (gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)) #86-Ubuntu SMP Fri Jan 17 17:25:58 UTC 2020

Docker plugin install information:
root@node43:/home/horatio# docker plugin install lade/linstor
Plugin "lade/linstor" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - mount: [/etc/linstor]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN]
Do you grant the above permissions? [y/N] y
latest: Pulling from lade/linstor
Digest: sha256:a938f71a27be81b465490f8069b99cb95bc1887bcde106a00972b4cf65c474b1
1e3a8ee5ca2d: Complete 
Error response from daemon: dial unix /run/docker/plugins/21a145a416b2f67311d44578dcf6496f91ec13dcae7c45fd62d4b9410f5b1ea1/linstor.sock: connect: no such file or directory

It looks like the LINSTOR socket problem.

Docker plugin list show:
root@node43:/home/horatio# docker plugin list  
ID             NAME                  DESCRIPTION                        ENABLED
21a145a416b2   lade/linstor:latest   Linstor volume plugin for Docker   false

I try to enable the plugin, it print the following information：
root@node43:/home/horatio# docker plugin enable 21a145a416b2
Error response from daemon: dial unix /run/docker/plugins/21a145a416b2f67311d44578dcf6496f91ec13dcae7c45fd62d4b9410f5b1ea1/linstor.sock: connect: no such file or directory

Configuration:
root@node43:/home/horatio# cat /etc/linstor/docker-volume.conf
[global]
controllers=192.168.1.10

Create volume test:
root@node43:/home/horatio# docker volume create -d lade/linstor:latest --opt fs=xfs --opt size=200M lsvol1 
Error response from daemon: create lsvol1: error looking up volume plugin lade/linstor:latest: plugin lade/linstor:latest found but disabled

If anyone need more information,please let me know!
Thanks

**Comment by beornf** [comment]
The Linstor plugin tag `lade/linstor:latest` is built and compatible with amd64 architecture only. The socket is missing since the Go binary crashed.

I've ran a new build on an amd64 host running an arm64 emulator. Can you pull the Linstor plugin tag `lade/linstor:arm64` and test it works on your Ubuntu system?

If you find further errors can you let me know your Docker version.

**Comment by kevinwd** [comment]
It works well  on my Ubuntu system.
Thank you for your help
