### ISSUE TITLE
Re-use a linstor volume

### ISSUE THREAD

**Issue by remoteweb** [beornf/linstor-docker-volume#13]
Hey there,

researching how we can get different docker containers to share the same linstor volume.

Initially, running the first container to use the linstor test volume works properly and the container has proper access to volume.
If we try to run a different container we get the following error.

```
[root@do2 linstor-docker-volume]# docker run -it -v test:/mnt/shared/ nginx sh
docker: Error response from daemon: error while mounting volume '': VolumeDriver.Mount: unable to get exclusive open on /dev/drbd1003.
ERRO[0000] error waiting for container: context canceled
```

Seems that this has been added in CSI plugin which unfortunately we can't yet use in Docker Swarm.
https://github.com/piraeusdatastore/linstor-csi/pull/35
https://github.com/piraeusdatastore/linstor-csi/pull/35/commits/b9372aff07e7664608f6080619bcf2f5cf3c8436
https://github.com/piraeusdatastore/linstor-csi/pull/35/commits/3890953b8a846d85ff2705d97d7833995c9c1b89

However, adding changes of b9372aff07e7664608f6080619bcf2f5cf3c8436 to driver.go leads to another error 

```
[root@do2 ~]# docker run -it -v test:/mnt/shared/ nginx sh
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/1d8eed5885c19913f0fcb283ac00efad1e79281d2c802f837a869fdc20c231b2/propagated-mount/test/data': VolumeDriver.Mount: mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs /dev/drbd1003 /var/lib/docker-volumes/linstor/test
Output: mount: /var/lib/docker-volumes/linstor/test: /dev/drbd1003 already mounted on /var/lib/docker-volumes/linstor/test.
```

Any thoughts on how we could possibly tackle this would be much appreciated.

**Comment by rck** [comment]
You simply can not do that. A DRBD volume can have multiple (==2) "users", but only if "someone" ensures that there is only one writer. Like in a cluster file system with distributed locking. The second use case for what we call "dual primary" in the DRBD world is live migration where for example libvirt/qemu makes sure that there is only one writer at a time. But you would have to tell DRBD that this is allowed. Otherwise it refuses to have multiple RW openers.

You certainly can not mount a regular file system on a DRBD device twice and expect any kind of consistency. You would be doomed. What people usually do is put something like NFS on top of DRBD devices.

**Comment by remoteweb** [comment]
thanks for your answer.

I think that it is valid design having multiple containers on same server to access the same volume.

For example in the atomic's docker LVM volume plugin multiple containers can access same volume. First container makes the mount while others will use the initial mount folder (/etc/docker/docker-lvm-plugin/volumename)

I totally understand why is wrong to have multiple servers - satellites accessing the same volume, which I agree is a wrong application of DRBD devices.

Having multiple containers in one host access the same space of storage is like having multiple processes to access a single mount. 

In host level we could mount a drbd device once in /mnt having multiple host processes access that mount at the same time.

I think the NFS protocol is needed when multiple hosts want to RW the same Linstor Volume..

**Comment by rck** [comment]
Yes, sure you are right. Don't know why I immediately jumped to the distributed use case.

Accessing the same Docker volume on the same host should work. Quite frankly I have not used the plugin in a long time, so @beornf might be the better candidate to actually debug that.

**Comment by remoteweb** [comment]
No worries, thanks for dropping in. This docker volume plugin is the up to date de facto when using Docker and Docker Swarm Envs :) .

**Comment by beornf** [comment]
I was uncertain whether the host use case is acceptable usage of Linstor/DRBD. Seeing as it's already merged in Linstor CSI it should be feasible for me to write a PR and do testing at some point.

**Comment by remoteweb** [comment]
That would be great, we can also provide testing for Docker and Docker Swarm environment.

**Comment by remoteweb** [comment]
.
