### ISSUE TITLE
Handle options from the Python based plugin

### ISSUE THREAD

**Issue by rck** [beornf/linstor-docker-volume#4]
I'd like to have this plugin - which should become the default for LINBIT - as much of a drop in replacement for the old python based plugin as possible. So I would like it to have the same CLI options as defined here: https://github.com/LINBIT/linstor-docker-volume/blob/master/README

**Comment by beornf** [comment]
I'm going to quickly rename a few properties that already exist. You can submit a PR to help me with supporting the fsopts parameter. I ported this logic which is a bit different to the python plugin https://github.com/LINBIT/linstor-csi/blob/d254c6f5f4ae446fbf33e355b23526eae4a0be4e/pkg/client/linstor.go#L859.

**Comment by rck** [comment]
I'm currently working on this one. I guess for now there are no changes needed from your side.
